### PR TITLE
update LICENSE in README.md too

### PR DESCRIPTION
**Pull request by vapier**
I couldn't find a "BSD-3-Clause" badge, but I've never used shields.io before.

### CODE REVIEW

**Comment by rmhrisk** [comment]
https://img.shields.io/badge/license-BSD-lightgrey.svg

**Comment by vapier** [comment]
are you saying you want to use lightgrey instead of green ?  i picked green as that's what other readme files in PeculiarVentures seems to use.

**Comment by rmhrisk** [comment]
Sorry, no. I thought you said you didn’t understand what to do for the logo. I didn’t look at the PR.

**Comment by vapier** [comment]
ping ... can this be merged now ?

**Pull request merged**
