### PR TITLE
Added TripleDES to decrypt private keys in PKCS#8

### PR DESCRIPTION
**Pull request by miguelrvs**
Using crypto-js https://github.com/brix/crypto-js @3.1.9

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
@miguelrvs No, if you need a specific algorithm then you should make your own crypto engine. I will not include it in a master branch.

**Comment by miguelrvs** [comment]
Yes, I read that somewhere. How do I make one CryptoEngine. Can you point me to the documentation?

**Comment by rmhrisk** [comment]
@miguelrvs yes, we don't want to include any crypto inside of PKIs, in general, we believe that native crypto should be used we also recognize that this is not possible for the weaker algorithms needed for PFX which is why I imagine your adding this.

We added `setEngin()`:

```
setEngine("newEngine", webcrypto, new CryptoEngine({ name: "", crypto: webcrypto, subtle: webcrypto.subtle }));
```

To allow for callers to use custom implementations for reasons like this, you could use this to use your own engine, or maybe you could use another project we have called `[webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner)` which is a provides a TS/JS webcrypto poliyfill.

In here we add support for non-standard algorithms, for example it does have [DES](https://github.com/PeculiarVentures/webcrypto-liner/search?utf8=%E2%9C%93&q=DES&type=).

If what you need algorithm wise isn't already in `webcrypto-liner` we would be happy to take it.

You can also just build a smaller CryptoEngine explicitly for PKIjs and specify it there.

**Comment by YuryStrozhevsky** [comment]
@miguelrvs In [**this example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NodePKCS12Example) you could find already existing crypto engine having 3-DES and working with PFX (PKCS#12).

**Comment by rmhrisk** [comment]
I think that we would probably take a PR that turned that into a cross platform example. What do you think yury?

**Comment by YuryStrozhevsky** [comment]
@rmhrisk I do prefer a PR with separate example for browser.

**Comment by rmhrisk** [comment]
ok.

@miguelrvs you could refactor this into an example for browser, similar to the node example, I think that would be useful.

**Comment by miguelrvs** [comment]
OK @rmhrisk, let me find some time to do it. Even with webcrypto-liner, we will need a custom engine (or modify the existing) because the OID are not included into the "normal" one.

**Comment by rmhrisk** [comment]
yes

**Pull request closed without merging**
