### PR TITLE
Added K-256 parameters

### PR DESCRIPTION
**Pull request by TJKoury**
Creating secp256k1 keys and generating certificates with them works just fine using [webcrypto ](https://github.com/PeculiarVentures/webcrypto) and [webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner).

Will add docs / tests (as required) if this pull looks like a good idea.

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
@TJKoury Ok, if you do need K-256 then I will accept the PR but only with at least basic tests.

**Comment by rmhrisk** [comment]
@TJKoury out of curiosity what will you be using these certificates for?

**Comment by TJKoury** [comment]
@YuryStrozhevsky Added a functional test.  What other tests would you like included?

**Comment by TJKoury** [comment]
@rmhrisk We have a few ideas that need proving out using public blockchains, starting with decentralized [space situational awareness](https://www.celestrak.com/NORAD/elements/).

**Comment by YuryStrozhevsky** [comment]
@TJKoury Since you want to make certificates using K-256 then it’s expected to have tests for certificates making. You need to modify “CertificateComplexExample”. And I bet your current changes would be not enough for making certificates. But will see.

**Comment by TJKoury** [comment]
@YuryStrozhevsky Ok, done, tested output with openssl.  Let me know if it works on your end.

**Comment by YuryStrozhevsky** [comment]
@TJKoury The certificate produced using your example is using P-256 curve even if I selected K-256. Also please do not include `bundle.js` in a patch. And do not re-format existing code.

**Comment by YuryStrozhevsky** [comment]
@TJKoury I was wrong regarding K-256. But other remarks need to be fixed. Also seems you broke Mocha tests for certificate example. The problem is that existing code is unsed in **three** different ways: 1) browser example; 2) Node.js Mocha test; 3) browser Mocha test. Not sure how but your changes should not broke other functionality. Plus since you append a specific packages in `package.json` inside example's folder you need to change `build:examples` script inside main `package.json`.

**Comment by TJKoury** [comment]
@YuryStrozhevsky Removed additional packages in package.json, simplified requirements, tests passing.

**Comment by YuryStrozhevsky** [comment]
@TJKoury Please exclude `bundle.js` from repository - this file is a "secondary product", not a source code. Plus exclude all the same "socundary product" files from `test`, `test\browser` and all other dirs under `examples`. For you better would be even clone initial PKI.js code again and just introduce your changes **just in one dir CertificateComplexExample** under `examples`.

And do not re-format existing code - just introduce your changes and that is all.

And I do suggest you to not include additional script into `rollup.config.js` - instead would be better to just include `<script>` tag right inside HTML file for the example.

**Comment by YuryStrozhevsky** [comment]
@TJKoury Also I think would be interesting to change [**this file**](https://github.com/PeculiarVentures/PKI.js/blob/master/test/browser/certificateComplexExample.html). By doing this you can introduce test for ECDSA curves at least in browser version of Mocha tests.

**Comment by TJKoury** [comment]
@YuryStrozhevsky Got busy, will fix soon.

**Pull request closed without merging**
