### PR TITLE
Update output script from ES5 to ES6

### PR DESCRIPTION
**Pull request by microshine**
This update fixes https://github.com/PeculiarVentures/PKI.js/issues/152 for NodeJS projects.

As I can see there is no problem with babel polyfill for Web projects. Because Web apps use bundlers and compile code using rollup and babel. In this case they can apply babel polyfills.

But there is a problem of using PKIjs for NodeJS projects. Users can not use PKIjs without adding babel polyfill. I fixed this problem by moving ES5 compiled script to ES6 commonjs bundle file. In this case PKIjs can be used in NodeJS projects without rollup, babel and it's polyfills. But there is only one limitation. NodeJS cannot be less than v8.

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
So, in order to resolve “issue” with ES5 code you are trying to use only ES6? Do you understand that Rollup does not produce ES5, only ES6? And do you understand that after your “perfect changes” all applications would use WHOLE pkijs code even after include of simple Attribute class? You “solved” your problem just because modern Node could run ES6 code and yes, it does not require any Babel :) Bravo, applauding.

**Comment by rmhrisk** [comment]
@YuryStrozhevsky if I understand correctly the proposed change here would result in the following::
1. This would remove precompiled ES5 from the package
2. This would mean that those users who simply "npm add pkijs" would work but they would take in all PKIjs when they do so.

Based on your explanation it would seem that #1 might be acceptable in that those users need to use a bundler and babel anyway and that would be derived from the ES6 code.

For #2 it would seem that this wouldnt be ideal for applications in production (being PKIjs is all there even if only one class is used) but would it prevent those applications opting to use rollup to build an optimized package?

**Comment by rmhrisk** [comment]
I had a chance to chat with @YuryStrozhevsky about this, I am still not sure what is the right trade-off here.

Since one can not mix and match ES6 and ES5 the support for ES6 in Node and Browsers is not the only factor; the real question on what to optimize for here is based on what the majority of applications use. 

For example, let's say I wrote my application in ES6 and it takes a dependency on some popular ES5 library. I still need to transpile my application down to ES5 so I can use that dependency.

This means today, our current situation of "add babel at the top of the stack if you are ES5" is probably more convenient for the application developer than having to add the build steps on how to transpile the ES6 to ES5 using babel.

Doing what is proposed in this PR would be superior if you were writing a ES6 pure application though, you could quickly get up and running with PKIjs with a "npm add" just like you do with other libraries and then when you build your production version of your application apply rollup to get the slim/minimal version of your package.

The questions are:
1. Do those who use PKIjs normally do pure ES5 applications?
2. Do those who use PKIjs normally do ES6 applications with ES5 dependencies?
3. Do those who use PKIjs normally do pure ES6 applications?

The problem I think we have here is we dont have any data to answer these questions so we have chosen something that sucks a little for everyone.

Did I summarize this correctly @YuryStrozhevsky?

**Comment by rmhrisk** [comment]
Following up to my conversation with @YuryStrozhevsky I mentioned above, it seems that it is worth noting that our current behavior, however awkward does force users down the path of using rollup which if they do the "natural thing" has the positive behavior of producing smaller code in production.

If we were to accept this PR, the user would be more easily able to produced bloated packages by not going through the extra step of applying rollup at the applicaiton layer.

**Comment by YuryStrozhevsky** [comment]
Closed as seems all came to conclusion that current way of working is better.

**Pull request closed without merging**
