### PR TITLE
Remove unused encodeFlag argument

### PR DESCRIPTION
**Pull request by lpinca**
The `toSchema()` method of these classes takes no arguments.

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
@lpinca Why do you think the "encodeFlag" is "unused"?

**Comment by YuryStrozhevsky** [comment]
@lpinca At least CRL class is using the flag. But anyway I do not see a reason to remove it from code - probably in a future it would be necessary.

**Comment by lpinca** [comment]
https://github.com/PeculiarVentures/PKI.js/blob/0c3f10839098e6cebfde0f06ab4c7835d265ad16/src/AlgorithmIdentifier.js#L145 
takes no arguments

https://github.com/PeculiarVentures/PKI.js/blob/0c3f10839098e6cebfde0f06ab4c7835d265ad16/src/OtherRevocationInfoFormat.js#L118

takes no arguments

https://github.com/PeculiarVentures/PKI.js/blob/0c3f10839098e6cebfde0f06ab4c7835d265ad16/src/SignerInfo.js#L276

takes no arguments

---

This is confusing to anyone reading `SignedData.prototype.toSchema()` which try to understand why the `encodeFlag` argument is passed to `AlgorithmIdentifier.prototype.toSchema()` for example.

In my opinion it should be added only when `AlgorithmIdentifier.prototype.toSchema()` and the others support it.

**Comment by lpinca** [comment]
Just to make my point clearer. This is not valid code in TypeScript and many other languages of course.

```ts
function bar() {
  return 10;
}

function foo(n: number) {
  return bar(n) + n;
}
```

The compiler returns the following error:

```
tsc index.ts
index.ts:6:14 - error TS2554: Expected 0 arguments, but got 1.

6   return bar(n) + n;
               ~


Found 1 error.
```

**Pull request closed without merging**
